// Command itempropsgen writes the vanilla stack sizes for the items in the runtime
// dictionary, which the dictionary itself does not carry.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
)

// defaultItemsURL is Allay's item table, extracted from the vanilla server. Pinned to a commit so
// regenerating is reproducible; bumping it is a deliberate change.
const defaultItemsURL = "https://raw.githubusercontent.com/AllayMC/Allay/1ce2686810255007ddc47129d025ce1a00099305/data/resources/items.json"

func main() {
	out := flag.String("o", "server/world/item_props.go", "generated Go output path")
	src := flag.String("items", defaultItemsURL, "URL or path of the vanilla item table")
	flag.Parse()

	data, err := readSource(*src)
	if err != nil {
		fatalf("read items: %v", err)
	}
	var decoded map[string]struct {
		MaxStackSize int `json:"maxStackSize"`
	}
	if err := json.Unmarshal(data, &decoded); err != nil {
		fatalf("decode items: %v", err)
	}

	names := make([]string, 0, len(decoded))
	for name := range decoded {
		names = append(names, name)
	}
	sort.Strings(names)

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "package world")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "// Code generated by cmd/itempropsgen from %s; DO NOT EDIT.\n\n", *src)
	fmt.Fprintln(&buf, "// vanillaStackSizes holds the highest count a stack of each vanilla item may hold.")
	fmt.Fprintln(&buf, "var vanillaStackSizes = map[string]int{")
	for _, name := range names {
		if size := decoded[name].MaxStackSize; size > 0 {
			fmt.Fprintf(&buf, "%q: %d,\n", name, size)
		}
	}
	fmt.Fprintln(&buf, "}")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
	fmt.Fprintf(os.Stderr, "wrote %d items to %s\n", len(names), *out)
}

func readSource(path string) ([]byte, error) {
	if strings.HasPrefix(path, "http://") || strings.HasPrefix(path, "https://") {
		resp, err := http.Get(path)
		if err != nil {
			return nil, err
		}
		defer resp.Body.Close()
		if resp.StatusCode < 200 || resp.StatusCode > 299 {
			return nil, fmt.Errorf("GET %s: %s", path, resp.Status)
		}
		return io.ReadAll(resp.Body)
	}
	return os.ReadFile(path)
}

func fatalf(format string, a ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", a...)
	os.Exit(1)
}
