// Command blockpropsgen writes the vanilla light and friction values that unknownBlock
// falls back to, for the blocks dragonfly has no implementation of.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
)

// defaultStatesURL is Allay's block state table, extracted from the vanilla server. Pinned to a commit so
// regenerating is reproducible; bumping it is a deliberate change.
const defaultStatesURL = "https://raw.githubusercontent.com/AllayMC/Allay/1ce2686810255007ddc47129d025ce1a00099305/data/resources/block_states.json"

type state struct {
	Name           string  `json:"name"`
	Friction       float64 `json:"friction"`
	LightDampening uint8   `json:"lightDampening"`
	LightEmission  uint8   `json:"lightEmission"`
}

func main() {
	out := flag.String("o", "server/world/block_props.go", "generated Go output path")
	src := flag.String("states", defaultStatesURL, "URL or path of the vanilla block state table")
	flag.Parse()

	data, err := readSource(*src)
	if err != nil {
		fatalf("read block states: %v", err)
	}
	var states []state
	if err := json.Unmarshal(data, &states); err != nil {
		fatalf("decode block states: %v", err)
	}

	// A block's states may disagree, mostly over light emitted while lit or charged. The
	// lowest is the resting value, and the one a block with no implementation cannot be
	// observed to have left.
	props := map[string]state{}
	for _, s := range states {
		prev, ok := props[s.Name]
		if !ok {
			props[s.Name] = s
			continue
		}
		if s.LightEmission < prev.LightEmission {
			prev.LightEmission = s.LightEmission
		}
		if s.LightDampening < prev.LightDampening {
			prev.LightDampening = s.LightDampening
		}
		props[s.Name] = prev
	}

	names := make([]string, 0, len(props))
	for name := range props {
		names = append(names, name)
	}
	sort.Strings(names)

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "package world")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "// Code generated by cmd/blockpropsgen from %s; DO NOT EDIT.\n\n", *src)
	fmt.Fprintln(&buf, "// unknownBlockProps holds the vanilla values an unknownBlock reports, keyed by block name.")
	fmt.Fprintln(&buf, "var unknownBlockProps = map[string]struct {")
	fmt.Fprintln(&buf, "\tfriction              float64")
	fmt.Fprintln(&buf, "\tdampening, emission   uint8")
	fmt.Fprintln(&buf, "}{")
	for _, name := range names {
		p := props[name]
		fmt.Fprintf(&buf, "%q: {%g, %d, %d},\n", name, p.Friction, p.LightDampening, p.LightEmission)
	}
	fmt.Fprintln(&buf, "}")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
	fmt.Fprintf(os.Stderr, "wrote %d blocks to %s\n", len(names), *out)
}

func readSource(path string) ([]byte, error) {
	if strings.HasPrefix(path, "http://") || strings.HasPrefix(path, "https://") {
		resp, err := http.Get(path)
		if err != nil {
			return nil, err
		}
		defer resp.Body.Close()
		if resp.StatusCode < 200 || resp.StatusCode > 299 {
			return nil, fmt.Errorf("GET %s: %s", path, resp.Status)
		}
		return io.ReadAll(resp.Body)
	}
	return os.ReadFile(path)
}

func fatalf(format string, a ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", a...)
	os.Exit(1)
}
