// Code generated by MockGen. DO NOT EDIT.
// Source: server/player/provider.go
//
// Generated by this command:
//
//	mockgen -source=server/player/provider.go -destination=mocks/player_provider.go -package=mocks -mock_names=Provider=MockPlayerProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	player "github.com/df-mc/dragonfly/server/player"
	world "github.com/df-mc/dragonfly/server/world"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPlayerProvider is a mock of Provider interface.
type MockPlayerProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerProviderMockRecorder
	isgomock struct{}
}

// MockPlayerProviderMockRecorder is the mock recorder for MockPlayerProvider.
type MockPlayerProviderMockRecorder struct {
	mock *MockPlayerProvider
}

// NewMockPlayerProvider creates a new mock instance.
func NewMockPlayerProvider(ctrl *gomock.Controller) *MockPlayerProvider {
	mock := &MockPlayerProvider{ctrl: ctrl}
	mock.recorder = &MockPlayerProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerProvider) EXPECT() *MockPlayerProviderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPlayerProvider) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPlayerProviderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPlayerProvider)(nil).Close))
}

// Load mocks base method.
func (m *MockPlayerProvider) Load(arg0 uuid.UUID, arg1 func(world.Dimension) *world.World) (player.Config, *world.World, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", arg0, arg1)
	ret0, _ := ret[0].(player.Config)
	ret1, _ := ret[1].(*world.World)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Load indicates an expected call of Load.
func (mr *MockPlayerProviderMockRecorder) Load(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockPlayerProvider)(nil).Load), arg0, arg1)
}

// Save mocks base method.
func (m *MockPlayerProvider) Save(arg0 uuid.UUID, data player.Config, w *world.World) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, data, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPlayerProviderMockRecorder) Save(arg0, data, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPlayerProvider)(nil).Save), arg0, data, w)
}
