// Code generated by MockGen. DO NOT EDIT.
// Source: server/session/session.go
//
// Generated by this command:
//
//	mockgen -source=server/session/session.go -destination=mocks/session_conn.go -package=mocks -mock_names=Conn=MockSessionConn
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	net "net"
	reflect "reflect"
	time "time"

	minecraft "github.com/sandertv/gophertunnel/minecraft"
	login "github.com/sandertv/gophertunnel/minecraft/protocol/login"
	packet "github.com/sandertv/gophertunnel/minecraft/protocol/packet"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionConn is a mock of Conn interface.
type MockSessionConn struct {
	ctrl     *gomock.Controller
	recorder *MockSessionConnMockRecorder
	isgomock struct{}
}

// MockSessionConnMockRecorder is the mock recorder for MockSessionConn.
type MockSessionConnMockRecorder struct {
	mock *MockSessionConn
}

// NewMockSessionConn creates a new mock instance.
func NewMockSessionConn(ctrl *gomock.Controller) *MockSessionConn {
	mock := &MockSessionConn{ctrl: ctrl}
	mock.recorder = &MockSessionConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionConn) EXPECT() *MockSessionConnMockRecorder {
	return m.recorder
}

// ChunkRadius mocks base method.
func (m *MockSessionConn) ChunkRadius() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChunkRadius")
	ret0, _ := ret[0].(int)
	return ret0
}

// ChunkRadius indicates an expected call of ChunkRadius.
func (mr *MockSessionConnMockRecorder) ChunkRadius() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChunkRadius", reflect.TypeOf((*MockSessionConn)(nil).ChunkRadius))
}

// ClientCacheEnabled mocks base method.
func (m *MockSessionConn) ClientCacheEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientCacheEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ClientCacheEnabled indicates an expected call of ClientCacheEnabled.
func (mr *MockSessionConnMockRecorder) ClientCacheEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientCacheEnabled", reflect.TypeOf((*MockSessionConn)(nil).ClientCacheEnabled))
}

// ClientData mocks base method.
func (m *MockSessionConn) ClientData() login.ClientData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientData")
	ret0, _ := ret[0].(login.ClientData)
	return ret0
}

// ClientData indicates an expected call of ClientData.
func (mr *MockSessionConnMockRecorder) ClientData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientData", reflect.TypeOf((*MockSessionConn)(nil).ClientData))
}

// Close mocks base method.
func (m *MockSessionConn) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSessionConnMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSessionConn)(nil).Close))
}

// Flush mocks base method.
func (m *MockSessionConn) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockSessionConnMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockSessionConn)(nil).Flush))
}

// IdentityData mocks base method.
func (m *MockSessionConn) IdentityData() login.IdentityData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentityData")
	ret0, _ := ret[0].(login.IdentityData)
	return ret0
}

// IdentityData indicates an expected call of IdentityData.
func (mr *MockSessionConnMockRecorder) IdentityData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityData", reflect.TypeOf((*MockSessionConn)(nil).IdentityData))
}

// Latency mocks base method.
func (m *MockSessionConn) Latency() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Latency")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Latency indicates an expected call of Latency.
func (mr *MockSessionConnMockRecorder) Latency() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Latency", reflect.TypeOf((*MockSessionConn)(nil).Latency))
}

// ReadPacket mocks base method.
func (m *MockSessionConn) ReadPacket() (packet.Packet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPacket")
	ret0, _ := ret[0].(packet.Packet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPacket indicates an expected call of ReadPacket.
func (mr *MockSessionConnMockRecorder) ReadPacket() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPacket", reflect.TypeOf((*MockSessionConn)(nil).ReadPacket))
}

// RemoteAddr mocks base method.
func (m *MockSessionConn) RemoteAddr() net.Addr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoteAddr")
	ret0, _ := ret[0].(net.Addr)
	return ret0
}

// RemoteAddr indicates an expected call of RemoteAddr.
func (mr *MockSessionConnMockRecorder) RemoteAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteAddr", reflect.TypeOf((*MockSessionConn)(nil).RemoteAddr))
}

// StartGameContext mocks base method.
func (m *MockSessionConn) StartGameContext(ctx context.Context, data minecraft.GameData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartGameContext", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartGameContext indicates an expected call of StartGameContext.
func (mr *MockSessionConnMockRecorder) StartGameContext(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartGameContext", reflect.TypeOf((*MockSessionConn)(nil).StartGameContext), ctx, data)
}

// WritePacket mocks base method.
func (m *MockSessionConn) WritePacket(pk packet.Packet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePacket", pk)
	ret0, _ := ret[0].(error)
	return ret0
}

// WritePacket indicates an expected call of WritePacket.
func (mr *MockSessionConnMockRecorder) WritePacket(pk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePacket", reflect.TypeOf((*MockSessionConn)(nil).WritePacket), pk)
}
