// Code generated by MockGen. DO NOT EDIT.
// Source: server/world/viewer.go
//
// Generated by this command:
//
//	mockgen -source=server/world/viewer.go -destination=mocks/world_viewer.go -package=mocks -mock_names=Viewer=MockWorldViewer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	cube "github.com/df-mc/dragonfly/server/block/cube"
	world "github.com/df-mc/dragonfly/server/world"
	chunk "github.com/df-mc/dragonfly/server/world/chunk"
	mgl64 "github.com/go-gl/mathgl/mgl64"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockWorldViewer is a mock of Viewer interface.
type MockWorldViewer struct {
	ctrl     *gomock.Controller
	recorder *MockWorldViewerMockRecorder
	isgomock struct{}
}

// MockWorldViewerMockRecorder is the mock recorder for MockWorldViewer.
type MockWorldViewerMockRecorder struct {
	mock *MockWorldViewer
}

// NewMockWorldViewer creates a new mock instance.
func NewMockWorldViewer(ctrl *gomock.Controller) *MockWorldViewer {
	mock := &MockWorldViewer{ctrl: ctrl}
	mock.recorder = &MockWorldViewerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorldViewer) EXPECT() *MockWorldViewerMockRecorder {
	return m.recorder
}

// HideEntity mocks base method.
func (m *MockWorldViewer) HideEntity(e world.Entity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HideEntity", e)
}

// HideEntity indicates an expected call of HideEntity.
func (mr *MockWorldViewerMockRecorder) HideEntity(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HideEntity", reflect.TypeOf((*MockWorldViewer)(nil).HideEntity), e)
}

// ViewBlockAction mocks base method.
func (m *MockWorldViewer) ViewBlockAction(pos cube.Pos, a world.BlockAction) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewBlockAction", pos, a)
}

// ViewBlockAction indicates an expected call of ViewBlockAction.
func (mr *MockWorldViewerMockRecorder) ViewBlockAction(pos, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewBlockAction", reflect.TypeOf((*MockWorldViewer)(nil).ViewBlockAction), pos, a)
}

// ViewBlockUpdate mocks base method.
func (m *MockWorldViewer) ViewBlockUpdate(pos cube.Pos, b world.Block, layer int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewBlockUpdate", pos, b, layer)
}

// ViewBlockUpdate indicates an expected call of ViewBlockUpdate.
func (mr *MockWorldViewerMockRecorder) ViewBlockUpdate(pos, b, layer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewBlockUpdate", reflect.TypeOf((*MockWorldViewer)(nil).ViewBlockUpdate), pos, b, layer)
}

// ViewBrewingUpdate mocks base method.
func (m *MockWorldViewer) ViewBrewingUpdate(prevBrewTime, brewTime time.Duration, prevFuelAmount, fuelAmount, prevFuelTotal, fuelTotal int32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewBrewingUpdate", prevBrewTime, brewTime, prevFuelAmount, fuelAmount, prevFuelTotal, fuelTotal)
}

// ViewBrewingUpdate indicates an expected call of ViewBrewingUpdate.
func (mr *MockWorldViewerMockRecorder) ViewBrewingUpdate(prevBrewTime, brewTime, prevFuelAmount, fuelAmount, prevFuelTotal, fuelTotal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewBrewingUpdate", reflect.TypeOf((*MockWorldViewer)(nil).ViewBrewingUpdate), prevBrewTime, brewTime, prevFuelAmount, fuelAmount, prevFuelTotal, fuelTotal)
}

// ViewChunk mocks base method.
func (m *MockWorldViewer) ViewChunk(pos world.ChunkPos, dim world.Dimension, blockEntities map[cube.Pos]world.Block, c *chunk.Chunk) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewChunk", pos, dim, blockEntities, c)
}

// ViewChunk indicates an expected call of ViewChunk.
func (mr *MockWorldViewerMockRecorder) ViewChunk(pos, dim, blockEntities, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewChunk", reflect.TypeOf((*MockWorldViewer)(nil).ViewChunk), pos, dim, blockEntities, c)
}

// ViewEmote mocks base method.
func (m *MockWorldViewer) ViewEmote(e world.Entity, emote uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewEmote", e, emote)
}

// ViewEmote indicates an expected call of ViewEmote.
func (mr *MockWorldViewerMockRecorder) ViewEmote(e, emote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewEmote", reflect.TypeOf((*MockWorldViewer)(nil).ViewEmote), e, emote)
}

// ViewEntity mocks base method.
func (m *MockWorldViewer) ViewEntity(e world.Entity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewEntity", e)
}

// ViewEntity indicates an expected call of ViewEntity.
func (mr *MockWorldViewerMockRecorder) ViewEntity(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewEntity", reflect.TypeOf((*MockWorldViewer)(nil).ViewEntity), e)
}

// ViewEntityAction mocks base method.
func (m *MockWorldViewer) ViewEntityAction(e world.Entity, a world.EntityAction) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewEntityAction", e, a)
}

// ViewEntityAction indicates an expected call of ViewEntityAction.
func (mr *MockWorldViewerMockRecorder) ViewEntityAction(e, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewEntityAction", reflect.TypeOf((*MockWorldViewer)(nil).ViewEntityAction), e, a)
}

// ViewEntityAnimation mocks base method.
func (m *MockWorldViewer) ViewEntityAnimation(e world.Entity, a world.EntityAnimation) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewEntityAnimation", e, a)
}

// ViewEntityAnimation indicates an expected call of ViewEntityAnimation.
func (mr *MockWorldViewerMockRecorder) ViewEntityAnimation(e, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewEntityAnimation", reflect.TypeOf((*MockWorldViewer)(nil).ViewEntityAnimation), e, a)
}

// ViewEntityArmour mocks base method.
func (m *MockWorldViewer) ViewEntityArmour(e world.Entity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewEntityArmour", e)
}

// ViewEntityArmour indicates an expected call of ViewEntityArmour.
func (mr *MockWorldViewerMockRecorder) ViewEntityArmour(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewEntityArmour", reflect.TypeOf((*MockWorldViewer)(nil).ViewEntityArmour), e)
}

// ViewEntityGameMode mocks base method.
func (m *MockWorldViewer) ViewEntityGameMode(e world.Entity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewEntityGameMode", e)
}

// ViewEntityGameMode indicates an expected call of ViewEntityGameMode.
func (mr *MockWorldViewerMockRecorder) ViewEntityGameMode(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewEntityGameMode", reflect.TypeOf((*MockWorldViewer)(nil).ViewEntityGameMode), e)
}

// ViewEntityItems mocks base method.
func (m *MockWorldViewer) ViewEntityItems(e world.Entity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewEntityItems", e)
}

// ViewEntityItems indicates an expected call of ViewEntityItems.
func (mr *MockWorldViewerMockRecorder) ViewEntityItems(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewEntityItems", reflect.TypeOf((*MockWorldViewer)(nil).ViewEntityItems), e)
}

// ViewEntityMovement mocks base method.
func (m *MockWorldViewer) ViewEntityMovement(e world.Entity, pos mgl64.Vec3, rot cube.Rotation, onGround bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewEntityMovement", e, pos, rot, onGround)
}

// ViewEntityMovement indicates an expected call of ViewEntityMovement.
func (mr *MockWorldViewerMockRecorder) ViewEntityMovement(e, pos, rot, onGround any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewEntityMovement", reflect.TypeOf((*MockWorldViewer)(nil).ViewEntityMovement), e, pos, rot, onGround)
}

// ViewEntityState mocks base method.
func (m *MockWorldViewer) ViewEntityState(e world.Entity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewEntityState", e)
}

// ViewEntityState indicates an expected call of ViewEntityState.
func (mr *MockWorldViewerMockRecorder) ViewEntityState(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewEntityState", reflect.TypeOf((*MockWorldViewer)(nil).ViewEntityState), e)
}

// ViewEntityTeleport mocks base method.
func (m *MockWorldViewer) ViewEntityTeleport(e world.Entity, pos mgl64.Vec3) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewEntityTeleport", e, pos)
}

// ViewEntityTeleport indicates an expected call of ViewEntityTeleport.
func (mr *MockWorldViewerMockRecorder) ViewEntityTeleport(e, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewEntityTeleport", reflect.TypeOf((*MockWorldViewer)(nil).ViewEntityTeleport), e, pos)
}

// ViewEntityVelocity mocks base method.
func (m *MockWorldViewer) ViewEntityVelocity(e world.Entity, vel mgl64.Vec3) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewEntityVelocity", e, vel)
}

// ViewEntityVelocity indicates an expected call of ViewEntityVelocity.
func (mr *MockWorldViewerMockRecorder) ViewEntityVelocity(e, vel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewEntityVelocity", reflect.TypeOf((*MockWorldViewer)(nil).ViewEntityVelocity), e, vel)
}

// ViewEntityWake mocks base method.
func (m *MockWorldViewer) ViewEntityWake(e world.Entity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewEntityWake", e)
}

// ViewEntityWake indicates an expected call of ViewEntityWake.
func (mr *MockWorldViewerMockRecorder) ViewEntityWake(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewEntityWake", reflect.TypeOf((*MockWorldViewer)(nil).ViewEntityWake), e)
}

// ViewFurnaceUpdate mocks base method.
func (m *MockWorldViewer) ViewFurnaceUpdate(prevCookTime, cookTime, prevRemainingFuelTime, remainingFuelTime, prevMaxFuelTime, maxFuelTime time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewFurnaceUpdate", prevCookTime, cookTime, prevRemainingFuelTime, remainingFuelTime, prevMaxFuelTime, maxFuelTime)
}

// ViewFurnaceUpdate indicates an expected call of ViewFurnaceUpdate.
func (mr *MockWorldViewerMockRecorder) ViewFurnaceUpdate(prevCookTime, cookTime, prevRemainingFuelTime, remainingFuelTime, prevMaxFuelTime, maxFuelTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewFurnaceUpdate", reflect.TypeOf((*MockWorldViewer)(nil).ViewFurnaceUpdate), prevCookTime, cookTime, prevRemainingFuelTime, remainingFuelTime, prevMaxFuelTime, maxFuelTime)
}

// ViewParticle mocks base method.
func (m *MockWorldViewer) ViewParticle(pos mgl64.Vec3, p world.Particle) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewParticle", pos, p)
}

// ViewParticle indicates an expected call of ViewParticle.
func (mr *MockWorldViewerMockRecorder) ViewParticle(pos, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewParticle", reflect.TypeOf((*MockWorldViewer)(nil).ViewParticle), pos, p)
}

// ViewSkin mocks base method.
func (m *MockWorldViewer) ViewSkin(e world.Entity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewSkin", e)
}

// ViewSkin indicates an expected call of ViewSkin.
func (mr *MockWorldViewerMockRecorder) ViewSkin(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewSkin", reflect.TypeOf((*MockWorldViewer)(nil).ViewSkin), e)
}

// ViewSound mocks base method.
func (m *MockWorldViewer) ViewSound(pos mgl64.Vec3, s world.Sound) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewSound", pos, s)
}

// ViewSound indicates an expected call of ViewSound.
func (mr *MockWorldViewerMockRecorder) ViewSound(pos, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewSound", reflect.TypeOf((*MockWorldViewer)(nil).ViewSound), pos, s)
}

// ViewTime mocks base method.
func (m *MockWorldViewer) ViewTime(t int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewTime", t)
}

// ViewTime indicates an expected call of ViewTime.
func (mr *MockWorldViewerMockRecorder) ViewTime(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewTime", reflect.TypeOf((*MockWorldViewer)(nil).ViewTime), t)
}

// ViewTimeCycle mocks base method.
func (m *MockWorldViewer) ViewTimeCycle(doDayLightCycle bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewTimeCycle", doDayLightCycle)
}

// ViewTimeCycle indicates an expected call of ViewTimeCycle.
func (mr *MockWorldViewerMockRecorder) ViewTimeCycle(doDayLightCycle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewTimeCycle", reflect.TypeOf((*MockWorldViewer)(nil).ViewTimeCycle), doDayLightCycle)
}

// ViewWeather mocks base method.
func (m *MockWorldViewer) ViewWeather(raining, thunder bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewWeather", raining, thunder)
}

// ViewWeather indicates an expected call of ViewWeather.
func (mr *MockWorldViewerMockRecorder) ViewWeather(raining, thunder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewWeather", reflect.TypeOf((*MockWorldViewer)(nil).ViewWeather), raining, thunder)
}

// ViewWorldSpawn mocks base method.
func (m *MockWorldViewer) ViewWorldSpawn(pos cube.Pos) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ViewWorldSpawn", pos)
}

// ViewWorldSpawn indicates an expected call of ViewWorldSpawn.
func (mr *MockWorldViewerMockRecorder) ViewWorldSpawn(pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewWorldSpawn", reflect.TypeOf((*MockWorldViewer)(nil).ViewWorldSpawn), pos)
}
