// Code generated by MockGen. DO NOT EDIT.
// Source: server/world/provider.go
//
// Generated by this command:
//
//	mockgen -source=server/world/provider.go -destination=mocks/world_provider.go -package=mocks -mock_names=Provider=MockWorldProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cube "github.com/df-mc/dragonfly/server/block/cube"
	world "github.com/df-mc/dragonfly/server/world"
	chunk "github.com/df-mc/dragonfly/server/world/chunk"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockWorldProvider is a mock of Provider interface.
type MockWorldProvider struct {
	ctrl     *gomock.Controller
	recorder *MockWorldProviderMockRecorder
	isgomock struct{}
}

// MockWorldProviderMockRecorder is the mock recorder for MockWorldProvider.
type MockWorldProviderMockRecorder struct {
	mock *MockWorldProvider
}

// NewMockWorldProvider creates a new mock instance.
func NewMockWorldProvider(ctrl *gomock.Controller) *MockWorldProvider {
	mock := &MockWorldProvider{ctrl: ctrl}
	mock.recorder = &MockWorldProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorldProvider) EXPECT() *MockWorldProviderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWorldProvider) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWorldProviderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWorldProvider)(nil).Close))
}

// LoadColumn mocks base method.
func (m *MockWorldProvider) LoadColumn(pos world.ChunkPos, dim world.Dimension) (*chunk.Column, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadColumn", pos, dim)
	ret0, _ := ret[0].(*chunk.Column)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadColumn indicates an expected call of LoadColumn.
func (mr *MockWorldProviderMockRecorder) LoadColumn(pos, dim any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadColumn", reflect.TypeOf((*MockWorldProvider)(nil).LoadColumn), pos, dim)
}

// LoadPlayerSpawnPosition mocks base method.
func (m *MockWorldProvider) LoadPlayerSpawnPosition(arg0 uuid.UUID) (cube.Pos, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPlayerSpawnPosition", arg0)
	ret0, _ := ret[0].(cube.Pos)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoadPlayerSpawnPosition indicates an expected call of LoadPlayerSpawnPosition.
func (mr *MockWorldProviderMockRecorder) LoadPlayerSpawnPosition(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPlayerSpawnPosition", reflect.TypeOf((*MockWorldProvider)(nil).LoadPlayerSpawnPosition), arg0)
}

// SavePlayerSpawnPosition mocks base method.
func (m *MockWorldProvider) SavePlayerSpawnPosition(arg0 uuid.UUID, pos cube.Pos) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePlayerSpawnPosition", arg0, pos)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePlayerSpawnPosition indicates an expected call of SavePlayerSpawnPosition.
func (mr *MockWorldProviderMockRecorder) SavePlayerSpawnPosition(arg0, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePlayerSpawnPosition", reflect.TypeOf((*MockWorldProvider)(nil).SavePlayerSpawnPosition), arg0, pos)
}

// SaveSettings mocks base method.
func (m *MockWorldProvider) SaveSettings(arg0 *world.Settings) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveSettings", arg0)
}

// SaveSettings indicates an expected call of SaveSettings.
func (mr *MockWorldProviderMockRecorder) SaveSettings(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSettings", reflect.TypeOf((*MockWorldProvider)(nil).SaveSettings), arg0)
}

// Settings mocks base method.
func (m *MockWorldProvider) Settings() *world.Settings {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Settings")
	ret0, _ := ret[0].(*world.Settings)
	return ret0
}

// Settings indicates an expected call of Settings.
func (mr *MockWorldProviderMockRecorder) Settings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Settings", reflect.TypeOf((*MockWorldProvider)(nil).Settings))
}

// StoreColumn mocks base method.
func (m *MockWorldProvider) StoreColumn(pos world.ChunkPos, dim world.Dimension, col *chunk.Column) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreColumn", pos, dim, col)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreColumn indicates an expected call of StoreColumn.
func (mr *MockWorldProviderMockRecorder) StoreColumn(pos, dim, col any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreColumn", reflect.TypeOf((*MockWorldProvider)(nil).StoreColumn), pos, dim, col)
}
